workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.guptaankit9.ankitproject"
    scripts:
      - name: Set Android SDK location
        script: |
          # Ensure the android directory exists before writing the local.properties file
          mkdir -p "$CM_BUILD_DIR/android"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: |
          npm install expo-cli@6.3.0
          npm install
      - name: Install sharp-cli globally
        script: |
          npm install -g sharp-cli
      - name: Install compatible expo-system-ui version
        script: |
          npm install expo-system-ui@3.0.0
      - name: Validate Metro Configuration
        script: |
          if [ ! -f metro.config.js ]; then
            echo "module.exports = require('@expo/metro-config').getDefaultConfig(__dirname);" > metro.config.js
          fi
      - name: Validate Expo project setup
        script: |
          npx expo doctor || true
      - name: Run Expo Prebuild
        script: |
          npx expo prebuild
      - name: Update Gradle version to 7.6
        script: |
          echo "Updating gradle-wrapper.properties to use Gradle 7.6..."
          # Replace any distributionUrl line pointing to a Gradle version with one that points to Gradle 7.6
          sed -i '' 's|distributionUrl=.*gradle-[0-9]*\.[0-9]*\.[0-9]*-bin.zip|distributionUrl=https://services.gradle.org/distributions/gradle-7.6-bin.zip|g' android/gradle/wrapper/gradle-wrapper.properties
          echo "Updated gradle-wrapper.properties:"
          cat android/gradle/wrapper/gradle-wrapper.properties
      - name: Build Android release
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
