version: 2.1
executors:
  android-executor:
    docker:
      - image: circleci/android:latest
    working_directory: ~/project
jobs:
  build-apk:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Update SDK
          command: sdkmanager --update
      - run:
          name: Accept Licenses
          command: yes | sdkmanager --licenses
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk
workflows:
  version: 2
  build:
    jobs:
      - build-apk